<template>
  <div v-if="show" class="al-magazine-overlay">
    <div class="al-magazine-container al-animate-scale-in">
      <!-- Header / Controls -->
      <div class="al-magazine-controls no-print">
        <h2 class="al-heading-4">{{ title }}</h2>
        <div class="al-controls-right">
          <button @click="printPdf" class="al-btn al-btn-primary">
            <Printer class="al-icon-sm" /> Print / Save PDF
          </button>
          <button @click="$emit('close')" class="al-btn al-btn-ghost al-btn-icon">
            <X class="al-icon-sm" />
          </button>
        </div>
      </div>

      <!-- PDF Content Area -->
      <div class="al-magazine-pages" id="al-pdf-content">
        <!-- Cover Page -->
        <div class="al-page al-cover-page">
          <div class="al-cover-content">
            <h1 class="al-cover-title">{{ curriculumName }}</h1>
            <h2 class="al-cover-subtitle">{{ moduleName }}</h2>
            <div class="al-cover-badge">{{ contentType }}</div>
          </div>
          <div class="al-cover-footer">
            Generated by AstraLearn AI
          </div>
        </div>

        <!-- Content Pages (Notes or Exercises) -->
        <div class="al-page al-content-page">
          <h2 class="al-page-heading">{{ title }}</h2>
          <div class="al-content-body">
            
            <template v-if="contentType === 'Notes'">
              <ul class="al-notes-list">
                <li v-for="(note, index) in items" :key="'note-'+index" class="al-note-item">
                  <span class="al-note-bullet"></span>
                  <p>{{ note }}</p>
                </li>
              </ul>
              <div v-if="!items || items.length === 0" class="al-empty-notes">
                No notes available for this module.
              </div>
            </template>
            
            <template v-else-if="contentType === 'Exercises'">
              <div v-for="(exercise, index) in items" :key="'ex-'+index" class="al-exercise-print-item">
                <h3 class="al-heading-4">Exercise {{ index + 1 }}</h3>
                <p class="al-exercise-prompt">{{ exercise.prompt }}</p>
                
                <div v-if="exercise.type === 'multiple-choice'" class="al-exercise-choices">
                  <div v-for="(opt, oIndex) in exercise.options" :key="oIndex" class="al-choice-item">
                    <div class="al-choice-circle"></div>
                    <span>{{ opt }}</span>
                  </div>
                </div>
                
                <div v-else-if="exercise.type === 'fill-blank'" class="al-exercise-blank">
                  ________________________________________________________
                </div>

                <div v-else-if="exercise.type === 'true-false'" class="al-exercise-choices">
                  <div class="al-choice-item"><div class="al-choice-circle"></div><span>True</span></div>
                  <div class="al-choice-item"><div class="al-choice-circle"></div><span>False</span></div>
                </div>

                <div v-else class="al-exercise-blank">
                  ________________________________________________________
                  <br><br>
                  ________________________________________________________
                </div>
              </div>
              <div v-if="!items || items.length === 0" class="al-empty-notes">
                No exercises available for this module.
              </div>
            </template>
            
          </div>
        </div>

        <!-- Back Page -->
        <div class="al-page al-back-page">
          <div class="al-back-content">
            <h2 class="al-heading-2">You're making great progress!</h2>
            <p class="al-body">Keep practicing everyday to achieve your goals.</p>
            
            <div class="al-about-box">
              <h3 class="al-heading-4">About AstraLearn</h3>
              <p class="al-body-sm">
                AstraLearn is a free, offline-first language learning platform built to help you learn efficiently with AI-generated curriculum.
              </p>
              <p class="al-body-sm al-mt-4">
                Designed & Developed by <strong>Mayuresh Mule</strong>
              </p>
              <a href="#" class="al-link">Portfolio</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Printer, X } from 'lucide-vue-next';

defineProps<{
  show: boolean;
  title: string;
  curriculumName: string;
  moduleName: string;
  contentType: 'Notes' | 'Exercises';
  items: any[];
}>();

defineEmits(['close']);

function printPdf() {
  window.print();
}
</script>

<style scoped>
/* Overlay and Controls */
.al-magazine-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.7);
  backdrop-filter: blur(4px);
  z-index: 1000;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: var(--al-space-6) 0;
  overflow-y: auto;
}

.al-magazine-container {
  width: 100%;
  max-width: 900px;
  background: var(--al-bg-tertiary);
  border-radius: var(--al-radius-lg);
  box-shadow: var(--al-shadow-xl);
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.al-magazine-controls {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--al-space-4) var(--al-space-6);
  background: var(--al-bg-primary);
  border-bottom: 1px solid var(--al-border-medium);
  position: sticky;
  top: 0;
  z-index: 10;
}

.al-controls-right {
  display: flex;
  align-items: center;
  gap: var(--al-space-4);
}

/* Document Pages wrapper */
.al-magazine-pages {
  padding: var(--al-space-8);
  display: flex;
  flex-direction: column;
  gap: var(--al-space-8);
  background: #e5e7eb; /* Neutral grey background for the viewer */
}

.dark .al-magazine-pages {
  background: #374151;
}

/* A4 Page Formatting */
.al-page {
  background: white;
  color: black;
  width: 210mm;
  min-height: 297mm;
  margin: 0 auto;
  padding: 20mm;
  box-shadow: 0 10px 25px rgba(0,0,0,0.1);
  position: relative;
  box-sizing: border-box;
}

/* Cover Page */
.al-cover-page {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  background: linear-gradient(135deg, #14b8a6, #0d9488);
  color: white;
}

.al-cover-content {
  border: 4px solid rgba(255,255,255,0.3);
  padding: 40mm 20mm;
  border-radius: 20px;
  width: 80%;
}

.al-cover-title {
  font-size: 3rem;
  font-weight: 800;
  margin-bottom: 1rem;
  font-family: var(--al-font-family);
}

.al-cover-subtitle {
  font-size: 1.8rem;
  font-weight: 400;
  opacity: 0.9;
  margin-bottom: 2rem;
}

.al-cover-badge {
  display: inline-block;
  background: white;
  color: #0d9488;
  padding: 10px 30px;
  border-radius: 50px;
  font-size: 1.2rem;
  font-weight: bold;
  text-transform: uppercase;
  letter-spacing: 2px;
}

.al-cover-footer {
  position: absolute;
  bottom: 30mm;
  opacity: 0.7;
  font-size: 1rem;
}

/* Content Page */
.al-page-heading {
  font-size: 2.2rem;
  font-weight: bold;
  color: #111827;
  border-bottom: 2px solid #14b8a6;
  padding-bottom: 10px;
  margin-bottom: 30px;
}

.al-content-body {
  font-size: 12pt;
  line-height: 1.8;
  color: #374151;
}

/* Notes Styles */
.al-notes-list {
  display: flex;
  flex-direction: column;
  gap: 20px;
  padding: 0;
  margin: 0;
  list-style: none;
}

.al-note-item {
  display: flex;
  gap: 15px;
  align-items: flex-start;
  background: #f9fafb;
  padding: 20px;
  border-radius: 8px;
  border-left: 4px solid #14b8a6;
}

.al-note-bullet {
  margin-top: 6px;
  min-width: 12px;
  height: 12px;
  background: #14b8a6;
  border-radius: 50%;
}

.al-empty-notes {
  text-align: center;
  padding: 40px;
  color: #6b7280;
  font-style: italic;
}

/* Exercise Print Styles */
.al-exercise-print-item {
  margin-bottom: 40px;
  page-break-inside: avoid;
}

.al-exercise-prompt {
  font-size: 1.2rem;
  font-weight: 500;
  margin-bottom: 15px;
  color: #1f2937;
}

.al-exercise-choices {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-left: 20px;
}

.al-choice-item {
  display: flex;
  align-items: center;
  gap: 15px;
}

.al-choice-circle {
  width: 20px;
  height: 20px;
  border: 2px solid #9ca3af;
  border-radius: 50%;
}

.al-exercise-blank {
  margin-top: 20px;
  color: #9ca3af;
  letter-spacing: 2px;
}

/* Back Page */
.al-back-page {
  display: flex;
  justify-content: center;
  align-items: center;
  background: #f8fafc;
}

.al-back-content {
  text-align: center;
  max-width: 500px;
}

.al-back-content h2 {
  color: #1e293b;
  margin-bottom: 10px;
}

.al-about-box {
  margin-top: 60px;
  background: white;
  padding: 40px;
  border-radius: 16px;
  box-shadow: 0 4px 6px rgba(0,0,0,0.05);
  border: 1px solid #e2e8f0;
}

.al-about-box h3 {
  color: #0f766e;
  margin-bottom: 15px;
}

/* Print CSS */
@media print {
  body * {
    visibility: hidden;
  }
  
  .al-magazine-pages, .al-magazine-pages * {
    visibility: visible;
  }
  
  .al-magazine-pages {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    margin: 0;
    padding: 0;
    background: transparent;
  }

  .al-page {
    margin: 0;
    box-shadow: none;
    page-break-after: always;
    width: 100%;
    height: 100vh;
  }
  
  .al-page:last-child {
    page-break-after: avoid;
  }

  .no-print {
    display: none !important;
  }

  /* Force background colors to print */
  * {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
}

/* Animations */
.al-animate-scale-in {
  animation: scaleIn 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}

@keyframes scaleIn {
  from { opacity: 0; transform: scale(0.95); }
  to { opacity: 1; transform: scale(1); }
}
</style>
